<?php

namespace Database\Seeders;

use App\Models\Enrollment;
use App\Models\NormalPlan;
use App\Models\Specialization;
use App\Models\User;
use Illuminate\Database\Seeder;

class EnrollmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $createdBy = User::query()->value('id');
        $specializationId = Specialization::query()->value('id');
        $normalCoverageId = NormalPlan::query()->value('id');

        if (!$createdBy || !$specializationId || !$normalCoverageId) {
            return;
        }

        $records = [
            [
                'customer_id_no' => 'IND-19000786-M03-0955',
                'money_rc_no' => 'MR-2026-0001',
                'agent_name' => 'Rahul Sharma',
                'agent_phone_no' => '9876543210',
                'doctor_name' => 'Dr. Arindam Roy',
                'doctor_address' => '12 Park Street, Kolkata',
                'country' => '101',
                'country_name' => 'India',
                'state' => '41',
                'state_name' => 'West Bengal',
                'city' => '5583',
                'city_name' => 'Kolkata',
                'postcode' => '700016',
                'mobile1' => '9123456780',
                'mobile2' => '03340001122',
                'doctor_email' => 'arindam.roy@mediforum.test',
                'dob' => '1984-03-14',
                'qualification' => 'MBBS, MD',
                'qualification_year' => [2007, 2012],
                'medical_registration_no' => 'WBMC-REG-458712',
                'year_of_reg' => '2013',
                'clinic_address' => 'Roy Polyclinic, 2nd Floor, Camac Street, Kolkata',
                'aadhar_card_no' => '234567891234',
                'pan_card_no' => 'ABCPR1234K',
                'specialization_id' => $specializationId,
                'payment_mode' => 'One Year',
                'plan' => 1,
                'plan_name' => 'Normal',
                'coverage_id' => $normalCoverageId,
                'service_amount' => 9000,
                'payment_amount' => 9000,
                'total_amount' => 18000,
                'payment_method' => 1,
                'payment_cheque' => 'CHQ-118822',
                'payment_bank_name' => 'HDFC Bank',
                'payment_branch_name' => 'Park Street',
                'payment_upi_transaction_id' => 'UTR202604090001',
                'payment_cash_date' => '2026-04-01',
                'bond_to_mail' => true,
                'auto_sms_enabled' => true,
                'created_by' => $createdBy,
            ],
            [
                'customer_id_no' => 'IND-19000786-M03-0956',
                'money_rc_no' => 'MR-2026-0002',
                'agent_name' => 'Sanjay Dutta',
                'agent_phone_no' => '9831122334',
                'doctor_name' => 'Dr. Priyanka Sen',
                'doctor_address' => '21 Lake Road, Kolkata',
                'country' => '101',
                'country_name' => 'India',
                'state' => '41',
                'state_name' => 'West Bengal',
                'city' => '5583',
                'city_name' => 'Kolkata',
                'postcode' => '700029',
                'mobile1' => '9230011122',
                'mobile2' => '03324561100',
                'doctor_email' => 'priyanka.sen@mediforum.test',
                'dob' => '1988-11-02',
                'qualification' => 'MBBS, DGO',
                'qualification_year' => [2010, 2014],
                'medical_registration_no' => 'WBMC-REG-761255',
                'year_of_reg' => '2015',
                'clinic_address' => 'Sen Women Care, 1st Floor, Ballygunge, Kolkata',
                'aadhar_card_no' => '345678912345',
                'pan_card_no' => 'DEFPS5678Q',
                'specialization_id' => $specializationId,
                'payment_mode' => 'Two Year',
                'plan' => 1,
                'plan_name' => 'Normal',
                'coverage_id' => $normalCoverageId,
                'service_amount' => 12000,
                'payment_amount' => 12000,
                'total_amount' => 24000,
                'payment_method' => 2,
                'payment_cheque' => 'CHQ-229933',
                'payment_bank_name' => 'ICICI Bank',
                'payment_branch_name' => 'Gariahat',
                'payment_upi_transaction_id' => 'UTR202604090002',
                'payment_cash_date' => '2026-04-02',
                'bond_to_mail' => true,
                'auto_sms_enabled' => true,
                'created_by' => $createdBy,
            ],
            [
                'customer_id_no' => 'IND-19000786-M03-0957',
                'money_rc_no' => 'MR-2026-0003',
                'agent_name' => 'Moumita Paul',
                'agent_phone_no' => '9903556677',
                'doctor_name' => 'Dr. Ritam Ghosh',
                'doctor_address' => '9 Sarat Bose Road, Kolkata',
                'country' => '101',
                'country_name' => 'India',
                'state' => '41',
                'state_name' => 'West Bengal',
                'city' => '5583',
                'city_name' => 'Kolkata',
                'postcode' => '700020',
                'mobile1' => '9073344556',
                'mobile2' => '03322115544',
                'doctor_email' => 'ritam.ghosh@mediforum.test',
                'dob' => '1982-07-19',
                'qualification' => 'MBBS, MS',
                'qualification_year' => [2005, 2011],
                'medical_registration_no' => 'WBMC-REG-998321',
                'year_of_reg' => '2012',
                'clinic_address' => 'Ghosh Surgical Clinic, Sarat Bose Road, Kolkata',
                'aadhar_card_no' => '456789123456',
                'pan_card_no' => 'GHIJK9012M',
                'specialization_id' => $specializationId,
                'payment_mode' => 'Three Year',
                'plan' => 1,
                'plan_name' => 'Normal',
                'coverage_id' => $normalCoverageId,
                'service_amount' => 16000,
                'payment_amount' => 16000,
                'total_amount' => 32000,
                'payment_method' => 3,
                'payment_cheque' => 'CHQ-330044',
                'payment_bank_name' => 'Axis Bank',
                'payment_branch_name' => 'Bhawanipore',
                'payment_upi_transaction_id' => 'UTR202604090003',
                'payment_cash_date' => '2026-04-03',
                'bond_to_mail' => true,
                'auto_sms_enabled' => true,
                'created_by' => $createdBy,
            ],
            [
                'customer_id_no' => 'IND-19000786-M03-0958',
                'money_rc_no' => 'MR-2026-0004',
                'agent_name' => 'Ankita Basu',
                'agent_phone_no' => '9830011100',
                'doctor_name' => 'Dr. Soumyajit Das',
                'doctor_address' => '3 Salt Lake Sector 1, Kolkata',
                'country' => '101',
                'country_name' => 'India',
                'state' => '41',
                'state_name' => 'West Bengal',
                'city' => '5583',
                'city_name' => 'Kolkata',
                'postcode' => '700064',
                'mobile1' => '9903001122',
                'mobile2' => '03323587766',
                'doctor_email' => 'soumyajit.das@mediforum.test',
                'dob' => '1986-12-09',
                'qualification' => 'MBBS, DNB',
                'qualification_year' => [2009, 2013],
                'medical_registration_no' => 'WBMC-REG-332210',
                'year_of_reg' => '2014',
                'clinic_address' => 'Das Diagnostic Center, Salt Lake, Kolkata',
                'aadhar_card_no' => '567891234567',
                'pan_card_no' => 'LMNOP3456R',
                'specialization_id' => $specializationId,
                'payment_mode' => 'Four Year',
                'plan' => 1,
                'plan_name' => 'Normal',
                'coverage_id' => $normalCoverageId,
                'service_amount' => 19000,
                'payment_amount' => 19000,
                'total_amount' => 38000,
                'payment_method' => 1,
                'payment_cheque' => 'CHQ-441155',
                'payment_bank_name' => 'SBI',
                'payment_branch_name' => 'Salt Lake',
                'payment_upi_transaction_id' => 'UTR202604090004',
                'payment_cash_date' => '2026-04-04',
                'bond_to_mail' => true,
                'auto_sms_enabled' => true,
                'created_by' => $createdBy,
            ],
            [
                'customer_id_no' => 'IND-19000786-M03-0959',
                'money_rc_no' => 'MR-2026-0005',
                'agent_name' => 'Koushik Mitra',
                'agent_phone_no' => '9748990011',
                'doctor_name' => 'Dr. Nabanita Mukherjee',
                'doctor_address' => '18 New Alipore, Kolkata',
                'country' => '101',
                'country_name' => 'India',
                'state' => '41',
                'state_name' => 'West Bengal',
                'city' => '5583',
                'city_name' => 'Kolkata',
                'postcode' => '700053',
                'mobile1' => '9874005566',
                'mobile2' => '03324019988',
                'doctor_email' => 'nabanita.mukherjee@mediforum.test',
                'dob' => '1990-05-28',
                'qualification' => 'BDS, MDS',
                'qualification_year' => [2011, 2016],
                'medical_registration_no' => 'WBMC-REG-778899',
                'year_of_reg' => '2016',
                'clinic_address' => 'Smile Care Dental Hub, New Alipore, Kolkata',
                'aadhar_card_no' => '678912345678',
                'pan_card_no' => 'QRSTU7890V',
                'specialization_id' => $specializationId,
                'payment_mode' => 'Five Year',
                'plan' => 1,
                'plan_name' => 'Normal',
                'coverage_id' => $normalCoverageId,
                'service_amount' => 22000,
                'payment_amount' => 22000,
                'total_amount' => 44000,
                'payment_method' => 2,
                'payment_cheque' => 'CHQ-552266',
                'payment_bank_name' => 'Kotak Mahindra Bank',
                'payment_branch_name' => 'Alipore',
                'payment_upi_transaction_id' => 'UTR202604090005',
                'payment_cash_date' => '2026-04-05',
                'bond_to_mail' => true,
                'auto_sms_enabled' => true,
                'created_by' => $createdBy,
            ],
        ];

        foreach ($records as $record) {
            Enrollment::updateOrCreate(
                ['customer_id_no' => $record['customer_id_no']],
                $record
            );
        }
    }
}
